on: push

name: CI Build

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: "sudo apt-get update -y && sudo apt-get -qq --yes --force-yes install latex2html make git lmodern texlive-latex-recommended texlive-fonts-extra"

      - name: Build pdf
        run: "make pdf html css"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./barinov-cv

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: barinov-cv.pdf
          path: barinov-cv.pdf
